locustfile = ./scenarios/http/gateway/existing_user_issue_virtual_card/scenario.py
spawn-rate = 5 #больше не тянет, поставил бы 30
run-time = 3m
headless = true
users = 100 #больше не тянет, поставил бы 300
html = ./scenarios/http/gateway/existing_user_issue_virtual_card/report.html